import { useState,useEffect,useRef } from 'react';
import Header from '../components/header/header';
import Head from 'next/head';
import RidesDetails from '../components/rides-details/rides-details';
import { getNearestRides,getUpComingRides } from '../utils/classify-rides';
import styles from '../styles/Home.module.css';

export default function Home() {
  
  const [state,setState] = useState({
    user: {},
    rides: []
  });
  
  useEffect(() => {
      fetchData();
      // console.log(state);
  }, []);

  const fetchData = async () => {
    try {
      const userResponse = await fetch("https://assessment.api.vweb.app/user");
      const user = await userResponse.json();
      const ridesResponse = await fetch("https://assessment.api.vweb.app/rides");
      const rides = await ridesResponse.json();
      setState({...state,user: user, rides: rides});
    } catch(err) {
      console.log(err);
      setTimeout(fetchData,10000);
    };
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Edvora - Rides</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header user={state.user} rides={state.rides}/>
      <RidesDetails rides={getUpComingRides(state.rides,state.user.station_code)}/>

    </div>
  )
}
